### ISSUE TITLE
question about lud

### ISSUE THREAD

**Issue by zjin-lcf** [FMarno/SYCL-LU-Decomposition#1]
Could you please explain the differences between your LUD and Rodinia's LUD ? Thanks.

**Comment by FMarno** [comment]
Hi @zjin-lcf,
Unfortunately I'm unfamiliar with Rodinia's LUD, but it you know any good resources I would be interested to read them.
From a quick google search it looks like Rodinia's LUD is solving the same problem.

If you were looking for some high performance LUD, I would look elsewhere. This implementation doesn't use a sparce martix representation, which I think could make a significant difference.

**Comment by zjin-lcf** [comment]
No problem. I would take a close look at your codes.
